spring:
  application:
    name: todolistrelazionale

  datasource:
    url: jdbc:mysql://localhost:3306/todolistrelazionale?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  
  # Configurazione server
  # server:
  #   port: 8080